### ISSUE TITLE
Page URL

### ISSUE THREAD

**Issue by Ghast17** [TheRealGitCub/fa-exodus-helper#4]
FurAffinity recently changed the watch list page URL and the application is still searching on the old one.

**Comment by TheRealGitCub** [comment]
Thanks for the report! I'll get the issue fixed tonight.

Thank you for using Exodus Helper.

On Sat, Jan 30, 2016, 4:24 PM Ghast17 <notifications@github.com> wrote:

> FurAffinity recently changed the watch list page URL and the application
> is still searching on the old one
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TheRealGitCub/fa-exodus-helper/issues/4>.
>
-- 

Kobi Tate

**Comment by TheRealGitCub** [comment]
Fixed!
